---
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(ggbiplot)
```

```{r, echo=FALSE}
Raw <- read.csv("~/Downloads/nbt.3154-S3-raw.csv", row.names = 1)
Nor <- read.csv("~/Downloads/nbt.3154-S3.csv", row.names = 1)
Norm <- as.matrix(Nor)
desc1=unlist(strsplit(rownames(Norm),"_"))
desc=desc1[seq(1,7867,2)]
gr4sfg=which(substr(rownames(Norm),1,5)=="4SFGA")
gr4sf=which(substr(rownames(Norm),1,4)=="4SGA")
gr1=which(substr(rownames(Norm),1,2)=="PS")
gr2=which(substr(rownames(Norm),1,2)=="NP")
gr3=which(substr(rownames(Norm),1,2)=="HF")
colscells=c("blue","green","orange","red","purple")
colnb=rep(0,3934)
colnb[gr1]=1
colnb[gr2]=2
colnb[gr3]=3
colnb[gr4sf]=4
colnb[gr4sfg]=5
typesort=rep(0,3934)
typesort[which(nchar(desc)<5 & substr(rownames(Norm),3,3)=="A")]="sortA"
typesort[which(nchar(desc)<5 & substr(rownames(Norm),3,3)=="B")]="sortB"
typesort[which(nchar(desc)>4)]="sortA"
ftable(typesort)
celltypes=as.factor(c("PS","NP","HF","4G","4GF")[colnb])
cellcol=colscells[colnb]
```


```{r}
colnames(Raw)
Raw["Type"] <- NA
Raw$Type <- celltypes
Pred <- read.csv("~/workspace/fate/results/norm/optimal_policy_transformed.csv")
total <- merge(x = Raw, y = Pred, by = 1:46, all.x = TRUE)

fix_decision <- function(profile) {
  if (profile[47] == '4GF' || profile[47] == '4G') {
    return(profile[47])
  }
  return(paste(profile[47], profile[48], sep = "->"))
}

total[, 48] <- apply(total, 1, fix_decision)

pr.raw <- prcomp(total[, 1:46], scale = FALSE)
pp <- ggbiplot(pr.raw, obs.scale = 1, var.scale = 1, scale = 1, groups = total[, 47], ellipse = TRUE, circle = TRUE)
pp
ggbiplot(pr.raw, obs.scale = 1, var.scale = 1, scale = 1, groups = total[, c("Decision")], ellipse = TRUE, circle = TRUE)


```
